-- FLOWGORILA FASE 2 — SUPABASE
-- Ejecuta TODO este archivo en Supabase > SQL Editor > New query.
-- Después ve a Authentication > URL Configuration y añade la URL de GitHub Pages.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 2 and 40),
  bio text not null default '' check (char_length(bio) <= 300),
  avatar_emoji text not null default '🧑‍🚀',
  role text not null default 'user' check (role in ('user','moderator','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 500),
  is_hidden boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.game_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  game text not null check (game in ('Trivia','Color Rush')),
  score integer not null check (score between 0 and 100000),
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  message text not null check (char_length(message) between 1 and 300),
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists comments_created_at_idx on public.comments(created_at desc);
create index if not exists comments_user_id_idx on public.comments(user_id);
create index if not exists game_scores_score_idx on public.game_scores(score desc);
create index if not exists game_scores_user_id_idx on public.game_scores(user_id);
create index if not exists notifications_user_id_idx on public.notifications(user_id);

alter table public.profiles enable row level security;
alter table public.comments enable row level security;
alter table public.game_scores enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "Profiles public read" on public.profiles;
create policy "Profiles public read" on public.profiles for select to anon, authenticated using (true);

drop policy if exists "Users insert own profile" on public.profiles;
create policy "Users insert own profile" on public.profiles for insert to authenticated
with check ((select auth.uid()) = id);

drop policy if exists "Users update own profile" on public.profiles;
create policy "Users update own profile" on public.profiles for update to authenticated
using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

drop policy if exists "Comments public read" on public.comments;
create policy "Comments public read" on public.comments for select to anon, authenticated
using (is_hidden = false);

drop policy if exists "Authenticated users create comments" on public.comments;
create policy "Authenticated users create comments" on public.comments for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users delete own comments" on public.comments;
create policy "Users delete own comments" on public.comments for delete to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Scores public read" on public.game_scores;
create policy "Scores public read" on public.game_scores for select to anon, authenticated using (true);

drop policy if exists "Users create own scores" on public.game_scores;
create policy "Users create own scores" on public.game_scores for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users read own notifications" on public.notifications;
create policy "Users read own notifications" on public.notifications for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users update own notifications" on public.notifications;
create policy "Users update own notifications" on public.notifications for update to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name, bio)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email,'@',1)),
    coalesce(new.raw_user_meta_data ->> 'bio','')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Realtime para comentarios:
alter publication supabase_realtime add table public.comments;
